[16.0][MIG] product_stock_coverage
coopiteasy/cie-stock pull request #6
Opened 2023-09-15 13:01 UTC by carmenbianca

## Description

Greatly improved the tests. There's one failing test. I want to mark it expectedFailure, but https://github.com/odoo/odoo/issues/135647 prevents me.

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=11145&action=475&active_id=492&model=project.task&view_type=form&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2023-10-05 13:49 UTC, robinkeunen approved these changes
LGTM 👍

2023-10-31 15:49 UTC, victor-champonnois requested changes
Functional review:
- Sales over computation range : computation OK
- Average daily sales over computation range : computation OK
- Stock coverage in days : computation NOK
- Effective sale price over computation range : OK

issue with stock coverage in days : 
I have a product with 28 unit of virtual available, and an average daily sale of of 0,07
![image](https://github.com/coopiteasy/cie-stock/assets/92781722/20595c36-b6bf-4849-9ceb-149cda4701d2)

In y opinion, the stock coverage in day should be 28/0,01=2800. But the stock coverage computed is 37 950. Is this an error ? 
tested on https://sandbox16.test.coopiteasy.be/web#id=5&cids=1&menu_id=217&action=348&model=product.template&view_type=form 
DB : sandbox16-test-supermarche-belge

2023-11-20 10:52 UTC, carmenbianca commented on product_stock_coverage/tests/test_stock_coverage.py
> +    def test_compute_stock_coverage_change_computation_range(self):
Use `@skip`

2024-01-22 16:18 UTC, carmenbianca commented
> In y opinion, the stock coverage in day should be 28/0,01=2800. But the stock coverage computed is 37 950. Is this an error ?

@victor-champonnois this is indeed the correct behaviour and the behaviour as written. However, when I open the debugger on line 100 of `product_template.py` of this module, this product's `virtual_available` is incomprehensibly much bigger. This explains why the computed value is much bigger. But I cannot comprehend why the `virtual_available` value is different in the debugger…

Is this limited to the demo data?

2025-07-07 13:24 UTC, victor-champonnois commented
I've tested again, it works well, both on demo data and manually created data. It works well now. Just a note :  the coverage is based on the forecasted quantity, not the on hand quantity.

2025-07-07 13:24 UTC, victor-champonnois approved these changes

2025-07-14 07:37 UTC, mihien commented
/ocabot merge nobump

2025-07-14 07:41 UTC, merged